import type { City } from "@/lib/seo-graph";

export const CITY_SUBURBS: Record<City, string[]> = {
  adelaide: [
    "Adelaide CBD",
    "North Adelaide",
    "Norwood",
    "Glenelg",
    "Unley",
    "Burnside",
    "Prospect",
    "Mitcham",
  ],
  bathurst: [
    "Bathurst CBD",
    "Kelso",
    "West Bathurst",
    "South Bathurst",
    "Eglinton",
    "Perthville",
    "Abercrombie",
  ],
  brisbane: [
    "Brisbane CBD",
    "New Farm",
    "Paddington",
    "Bulimba",
    "Hamilton",
    "Toowong",
    "Indooroopilly",
    "Ascot",
  ],
  "byron-bay": [
    "Byron Bay",
    "Suffolk Park",
    "Bangalow",
    "Mullumbimby",
    "Lennox Head",
    "Federal",
    "Ewingsdale",
  ],
  canberra: [
    "Canberra City",
    "Braddon",
    "Kingston",
    "Manuka",
    "Forrest",
    "Yarralumla",
    "Deakin",
    "Griffith",
  ],
  "central-coast": [
    "Gosford",
    "Terrigal",
    "Erina",
    "Avoca Beach",
    "Woy Woy",
    "Wamberal",
    "Killcare",
    "Wyong",
  ],
  "coffs-harbour": [
    "Coffs Harbour CBD",
    "Sawtell",
    "Boambee",
    "Korora",
    "Park Beach",
    "Toormina",
    "Bonville",
  ],
  "gold-coast": [
    "Surfers Paradise",
    "Broadbeach",
    "Burleigh Heads",
    "Mermaid Beach",
    "Palm Beach",
    "Coolangatta",
    "Robina",
    "Bundall",
  ],
  "hunter-valley": [
    "Cessnock",
    "Pokolbin",
    "Maitland",
    "Singleton",
    "Branxton",
    "Lovedale",
    "Rothbury",
    "Muswellbrook",
  ],
  melbourne: [
    "Melbourne CBD",
    "South Yarra",
    "Toorak",
    "Brighton",
    "Carlton",
    "Richmond",
    "Hawthorn",
    "St Kilda",
  ],
  newcastle: [
    "Newcastle East",
    "Cooks Hill",
    "The Junction",
    "Merewether",
    "Hamilton",
    "New Lambton",
    "Adamstown",
    "Charlestown",
  ],
  orange: [
    "Orange CBD",
    "Bletchington",
    "Glenroi",
    "Calare",
    "East Orange",
    "Lucknow",
    "Spring Hill",
  ],
  perth: [
    "Perth CBD",
    "Subiaco",
    "Cottesloe",
    "Claremont",
    "Nedlands",
    "Fremantle",
    "Mount Lawley",
    "Leederville",
  ],
  "port-macquarie": [
    "Port Macquarie CBD",
    "Settlement Point",
    "Lighthouse Beach",
    "Lake Cathie",
    "Wauchope",
    "Sancrox",
  ],
  sydney: [
    "Sydney CBD",
    "Mosman",
    "Paddington",
    "Surry Hills",
    "Bondi",
    "Manly",
    "Double Bay",
    "Newtown",
  ],
  wollongong: [
    "Wollongong CBD",
    "North Wollongong",
    "Thirroul",
    "Bulli",
    "Figtree",
    "Corrimal",
    "Fairy Meadow",
    "Helensburgh",
  ],
};

export function suburbsForCity(city: City): string {
  return CITY_SUBURBS[city].join(", ");
}
