import { FOUNDING_YEAR } from "@/lib/business";

import type { LocationDefinition } from "./types";

export const LOCATIONS: readonly LocationDefinition[] = [
  {
    id: "newcastle",
    slug: "newcastle",
    name: "Newcastle",
    state: "NSW",
    region: "NSW Coastal",
    tier: 1,
    areaDescription:
      "Newcastle is where SteepWood lives and works. Our workshop and design studio are based here, which means every piece of joinery we make for a Newcastle home or business is built within driving distance of the people who will use it.",
    populationServed: "Greater Newcastle and Hunter Region",
    driveTimeFromNewcastle: "0 — Newcastle is home",
    driveTimeShort: "local",
    metaTitle: "Custom Joinery Newcastle NSW | SteepWood",
    metaDescription:
      "Newcastle's premium custom joinery workshop. Kitchens, wardrobes, vanities, commercial joinery. Local craftsmanship, fixed-price quotes. Free in-home visit.",
    h1: `Custom Joinery in Newcastle NSW — Local Craftsmanship Since ${FOUNDING_YEAR}`,
    heroImagePath: "/images/locations/newcastle-hero.jpg",
    ogImagePath: "/og/locations/newcastle-og.jpg",
  },
  {
    id: "sydney",
    slug: "sydney",
    name: "Sydney",
    state: "NSW",
    region: "Capital City",
    tier: 1,
    areaDescription:
      "Sydney is Australia's largest joinery market and one of the most discerning. SteepWood services Sydney from our Newcastle workshop — two hours up the M1 — bringing high-end design sensibilities together with Hunter-based manufacturing capacity and pricing.",
    populationServed: "Greater Sydney metropolitan area",
    driveTimeFromNewcastle: "~2 hours via M1",
    driveTimeShort: "2hr",
    metaTitle: "Custom Joinery Sydney NSW | SteepWood",
    metaDescription:
      "Custom kitchens, wardrobes and bespoke joinery for Sydney homes. Newcastle-crafted, 2hr from our workshop. Free in-home design consultation and quote.",
    h1: "Custom Joinery in Sydney NSW — Newcastle-Crafted, Sydney-Delivered",
    heroImagePath: "/images/locations/sydney-hero.jpg",
    ogImagePath: "/og/locations/sydney-og.jpg",
  },
  {
    id: "canberra",
    slug: "canberra",
    name: "Canberra",
    state: "ACT",
    region: "Capital City",
    tier: 1,
    areaDescription:
      "Canberra is a high-income, design-literate market with a notable shortage of premium joinery options. SteepWood services Canberra from our Newcastle workshop with the same fixed-price contract, materials palette, and manufacturing standards we apply to local projects.",
    populationServed: "Australian Capital Territory and Queanbeyan surrounds",
    driveTimeFromNewcastle: "~5 hours",
    driveTimeShort: "5hr",
    metaTitle: "Custom Joinery Canberra ACT | SteepWood",
    metaDescription:
      "Custom kitchens, wardrobes and bespoke joinery for Canberra homes. Newcastle-crafted, ACT-delivered. Free design consultation, fixed-price quotes.",
    h1: "Custom Joinery in Canberra ACT — Bespoke Cabinetry for the Capital",
    heroImagePath: "/images/locations/canberra-hero.jpg",
    ogImagePath: "/og/locations/canberra-og.jpg",
  },
  {
    id: "melbourne",
    slug: "melbourne",
    name: "Melbourne",
    state: "VIC",
    region: "Capital City",
    tier: 1,
    areaDescription:
      "Melbourne homeowners and designers expect joinery with genuine design literacy — from Hamptons kitchens in Brighton to handleless contemporary cabinetry in South Yarra. SteepWood manufactures in Newcastle and delivers to Melbourne via freight.",
    populationServed: "Greater Melbourne metropolitan area",
    driveTimeFromNewcastle: "Freight delivery (~9 hours road; 1-day truck transit)",
    driveTimeShort: "freight-delivered",
    metaTitle: "Custom Joinery Melbourne VIC | SteepWood",
    metaDescription:
      "Custom kitchens, wardrobes, bespoke joinery for Melbourne homes. Newcastle-crafted, freight-delivered. Toorak, Brighton, Hawthorn, South Yarra and more.",
    h1: "Custom Joinery in Melbourne VIC — Newcastle Craft, Melbourne Style",
    heroImagePath: "/images/locations/melbourne-hero.jpg",
    ogImagePath: "/og/locations/melbourne-og.jpg",
  },
  {
    id: "central-coast",
    slug: "central-coast",
    name: "Central Coast",
    state: "NSW",
    region: "NSW Coastal",
    tier: 2,
    areaDescription:
      "The Central Coast sits between Sydney and Newcastle — a coastal market of family homes, holiday properties, and growing new-build estates from Gosford to Terrigal and The Entrance. SteepWood is just over an hour from most Central Coast suburbs.",
    populationServed: "Central Coast NSW — Gosford to The Entrance",
    driveTimeFromNewcastle: "~1 hour 15 minutes via M1",
    driveTimeShort: "1hr",
    metaTitle: "Custom Joinery Central Coast NSW | SteepWood",
    metaDescription:
      "Custom joinery for Central Coast homes — Gosford, Terrigal, Avoca, The Entrance. Newcastle-crafted, 1hr from our workshop. Free consultations.",
    h1: "Custom Joinery on the Central Coast — Coastal Homes, Crafted to Last",
    heroImagePath: "/images/locations/central-coast-hero.jpg",
    ogImagePath: "/og/locations/central-coast-og.jpg",
  },
  {
    id: "hunter-valley",
    slug: "hunter-valley",
    name: "Hunter Valley",
    state: "NSW",
    region: "NSW Inland",
    tier: 2,
    areaDescription:
      "The Hunter Valley is SteepWood's backyard — wine country estates, cellar doors, and premium country homes from Pokolbin to Lovedale. We serve the region with local consultations and fast turnaround from our Newcastle workshop.",
    populationServed: "Hunter Valley wine country and surrounds",
    driveTimeFromNewcastle: "~45 minutes",
    driveTimeShort: "45min",
    metaTitle: "Custom Joinery Hunter Valley NSW | SteepWood",
    metaDescription:
      "Custom joinery for Hunter Valley homes and cellar doors — Pokolbin, Cessnock, Lovedale, Singleton. Newcastle-based, free local consultations.",
    h1: "Custom Joinery in the Hunter Valley — From Cellar Door to Country Estate",
    heroImagePath: "/images/locations/hunter-valley-hero.jpg",
    ogImagePath: "/og/locations/hunter-valley-og.jpg",
  },
  {
    id: "gold-coast",
    slug: "gold-coast",
    name: "Gold Coast",
    state: "QLD",
    region: "Capital City",
    tier: 2,
    areaDescription:
      "The Gold Coast is one of Australia's highest-income coastal markets — luxury apartments, waterfront homes, and high-end renovations from Broadbeach to Mermaid Beach. SteepWood manufactures in Newcastle and freight-delivers to the Gold Coast.",
    populationServed: "Gold Coast metropolitan area",
    driveTimeFromNewcastle: "~9 hours (freight delivery)",
    driveTimeShort: "freight-delivered",
    metaTitle: "Custom Joinery Gold Coast QLD | SteepWood",
    metaDescription:
      "Custom kitchens, wardrobes, and bespoke joinery for Gold Coast homes. Newcastle-crafted, freight-delivered. Broadbeach, Mermaid, Surfers Paradise.",
    h1: "Custom Joinery on the Gold Coast — High-End Coastal Cabinetry",
    heroImagePath: "/images/locations/gold-coast-hero.jpg",
    ogImagePath: "/og/locations/gold-coast-og.jpg",
  },
  {
    id: "wollongong",
    slug: "wollongong",
    name: "Wollongong",
    state: "NSW",
    region: "NSW Coastal",
    tier: 2,
    areaDescription:
      "Wollongong and the Illawarra combine coastal lifestyle with Sydney spillover demand — from Thirroul and Austinmer beach cottages to Kiama and Shellharbour family homes. SteepWood delivers from Newcastle in roughly three and a half hours.",
    populationServed: "Wollongong and Illawarra region",
    driveTimeFromNewcastle: "~3.5 hours",
    driveTimeShort: "3.5hr",
    metaTitle: "Custom Joinery Wollongong NSW | SteepWood",
    metaDescription:
      "Custom joinery for Wollongong and Illawarra homes — Thirroul, Austinmer, Kiama. Newcastle-crafted, ~3.5hr delivery. Free consultations.",
    h1: "Custom Joinery in Wollongong & the Illawarra — Newcastle Craft, Coastal Quality",
    heroImagePath: "/images/locations/wollongong-hero.jpg",
    ogImagePath: "/og/locations/wollongong-og.jpg",
  },
  {
    id: "brisbane",
    slug: "brisbane",
    name: "Brisbane",
    state: "QLD",
    region: "Capital City",
    tier: 2,
    areaDescription:
      "Brisbane's joinery market spans Queenslander restorations in Paddington and Bulimba, executive homes in New Farm and Chelmer, and contemporary apartments across the inner city. SteepWood manufactures in Newcastle and freight-delivers to Brisbane.",
    populationServed: "Greater Brisbane metropolitan area",
    driveTimeFromNewcastle: "~9 hours (freight delivery)",
    driveTimeShort: "freight-delivered",
    metaTitle: "Custom Joinery Brisbane QLD | SteepWood",
    metaDescription:
      "Custom kitchens, wardrobes and bespoke joinery for Brisbane homes. Newcastle-crafted, freight-delivered. New Farm, Paddington, Bulimba, Chelmer.",
    h1: "Custom Joinery in Brisbane QLD — Premium Cabinetry, Newcastle-Crafted",
    heroImagePath: "/images/locations/brisbane-hero.jpg",
    ogImagePath: "/og/locations/brisbane-og.jpg",
  },
  {
    id: "perth",
    slug: "perth",
    name: "Perth",
    state: "WA",
    region: "Capital City",
    tier: 2,
    areaDescription:
      "Perth's premium joinery market — Cottesloe, Mosman Park, Subiaco, Floreat, and Dalkeith — values quality craftsmanship and reliable delivery. SteepWood manufactures in Newcastle and ships to Perth via dedicated freight.",
    populationServed: "Greater Perth metropolitan area",
    driveTimeFromNewcastle: "Freight only (3–5 day transit)",
    driveTimeShort: "freight-delivered",
    metaTitle: "Custom Joinery Perth WA | SteepWood",
    metaDescription:
      "Custom kitchens, wardrobes, bespoke joinery for Perth homes. Newcastle-crafted, freight-delivered. Cottesloe, Mosman Park, Subiaco, Floreat, Dalkeith.",
    h1: "Custom Joinery in Perth WA — Premium Cabinetry, Newcastle-Made",
    heroImagePath: "/images/locations/perth-hero.jpg",
    ogImagePath: "/og/locations/perth-og.jpg",
  },
  {
    id: "byron-bay",
    slug: "byron-bay",
    name: "Byron Bay",
    state: "NSW",
    region: "NSW Coastal",
    tier: 3,
    areaDescription:
      "Byron Bay and the Northern Rivers attract affluent lifestyle buyers who expect joinery that matches the coastal aesthetic — natural timbers, Hamptons profiles, and durable finishes for salt-air environments.",
    populationServed: "Byron Bay and Northern Rivers NSW",
    driveTimeFromNewcastle: "~9 hours (freight)",
    driveTimeShort: "freight-delivered",
    metaTitle: "Custom Joinery Byron Bay NSW | SteepWood",
    metaDescription:
      "Custom joinery for Byron Bay and Northern Rivers homes — Suffolk Park, Bangalow, Mullumbimby. Newcastle-crafted, freight to NSW Northern Rivers.",
    h1: "Custom Joinery in Byron Bay — Coastal Craft, Made to Last",
    heroImagePath: "/images/locations/byron-bay-hero.jpg",
    ogImagePath: "/og/locations/byron-bay-og.jpg",
  },
  {
    id: "port-macquarie",
    slug: "port-macquarie",
    name: "Port Macquarie",
    state: "NSW",
    region: "NSW Coastal",
    tier: 3,
    areaDescription:
      "Port Macquarie is a thriving sea-change destination with strong demand for kitchen and wardrobe upgrades in established homes and new coastal estates from Town Beach to Lighthouse Beach.",
    populationServed: "Port Macquarie and Hastings region",
    driveTimeFromNewcastle: "~3 hours",
    driveTimeShort: "3hr",
    metaTitle: "Custom Joinery Port Macquarie NSW | SteepWood",
    metaDescription:
      "Custom joinery for Port Macquarie homes — Town Beach, Lighthouse Beach, Settlement City. Newcastle-crafted, ~3hr delivery. Free design consultations.",
    h1: "Custom Joinery in Port Macquarie — Sea-Change Homes, Premium Cabinetry",
    heroImagePath: "/images/locations/port-macquarie-hero.jpg",
    ogImagePath: "/og/locations/port-macquarie-og.jpg",
  },
  {
    id: "coffs-harbour",
    slug: "coffs-harbour",
    name: "Coffs Harbour",
    state: "NSW",
    region: "NSW Coastal",
    tier: 3,
    areaDescription:
      "Coffs Harbour, Sawtell, Bellingen, and Woolgoolga form a mid-north coast hub where coastal homes and hinterland properties both demand quality custom joinery for kitchens, wardrobes, and renovations.",
    populationServed: "Coffs Coast and mid-north coast NSW",
    driveTimeFromNewcastle: "~5 hours",
    driveTimeShort: "5hr",
    metaTitle: "Custom Joinery Coffs Harbour NSW | SteepWood",
    metaDescription:
      "Custom joinery for Coffs Harbour, Sawtell, Bellingen, Woolgoolga. Newcastle-crafted, ~5hr delivery. Free design consultations on larger projects.",
    h1: "Custom Joinery in Coffs Harbour — Mid North Coast Craft",
    heroImagePath: "/images/locations/coffs-harbour-hero.jpg",
    ogImagePath: "/og/locations/coffs-harbour-og.jpg",
  },
  {
    id: "adelaide",
    slug: "adelaide",
    name: "Adelaide",
    state: "SA",
    region: "Capital City",
    tier: 3,
    areaDescription:
      "Adelaide's established suburbs — North Adelaide, Norwood, Unley, and Glenelg — value bespoke joinery for heritage renovations and contemporary new builds alike. SteepWood manufactures in Newcastle and freight-delivers to Adelaide.",
    populationServed: "Greater Adelaide metropolitan area",
    driveTimeFromNewcastle: "Freight only (2–3 day transit)",
    driveTimeShort: "freight-delivered",
    metaTitle: "Custom Joinery Adelaide SA | SteepWood",
    metaDescription:
      "Custom kitchens, wardrobes, bespoke joinery for Adelaide homes. Newcastle-crafted, freight-delivered. North Adelaide, Norwood, Unley, Glenelg.",
    h1: "Custom Joinery in Adelaide SA — Bespoke Cabinetry, Newcastle-Crafted",
    heroImagePath: "/images/locations/adelaide-hero.jpg",
    ogImagePath: "/og/locations/adelaide-og.jpg",
  },
  {
    id: "bathurst",
    slug: "bathurst",
    name: "Bathurst",
    state: "NSW",
    region: "NSW Inland",
    tier: 3,
    areaDescription:
      "Bathurst combines Federation heritage homes, country contemporary new builds, and a fast-growing construction market in the Central West. SteepWood delivers from Newcastle in roughly three and a half hours.",
    populationServed: "Bathurst and Central West NSW",
    driveTimeFromNewcastle: "~3.5 hours",
    driveTimeShort: "3.5hr",
    metaTitle: "Custom Joinery Bathurst NSW | SteepWood",
    metaDescription:
      "Custom joinery for Bathurst and Central West homes — heritage Federation, country contemporary, new-build. Newcastle-crafted, ~3.5hr delivery.",
    h1: "Custom Joinery in Bathurst NSW — Heritage Country, Modern Craft",
    heroImagePath: "/images/locations/bathurst-hero.jpg",
    ogImagePath: "/og/locations/bathurst-og.jpg",
  },
  {
    id: "orange",
    slug: "orange",
    name: "Orange",
    state: "NSW",
    region: "NSW Inland",
    tier: 3,
    areaDescription:
      "Orange is a high-income wine country centre where Federation cottages, contemporary country homes, and new-build estates all demand premium custom joinery. SteepWood delivers from Newcastle in roughly three and a half hours.",
    populationServed: "Orange and Central West wine country",
    driveTimeFromNewcastle: "~3.5 hours",
    driveTimeShort: "3.5hr",
    metaTitle: "Custom Joinery Orange NSW | SteepWood",
    metaDescription:
      "Custom joinery for Orange and Central West homes — wine country contemporary, heritage Federation, new-build. Newcastle-crafted, ~3.5hr delivery.",
    h1: "Custom Joinery in Orange NSW — Wine Country Craft",
    heroImagePath: "/images/locations/orange-hero.jpg",
    ogImagePath: "/og/locations/orange-og.jpg",
  },
] as const;

export function getLocationDefinition(
  slug: string,
): LocationDefinition | undefined {
  return LOCATIONS.find((location) => location.slug === slug);
}
